#!/bin/bash
BORG_REPO="/to/borgrepo/dir"
export BORG_PASSPHRASE="INSERT PASSPHRASE" 
borg create --stats $BORG_REPO/::btrfs-backup-{now:%Y-%m-%d_%H-%M} /.btrfs
borg prune -v --list --keep-daily 7 --keep-weekly 4 --keep-monthly 6 $BORG_REPO && borg compact $BORG_REPO
